### ISSUE TITLE
Breaking change extract method in version 3.3.5

### ISSUE THREAD

**Issue by floriandorre** [timcera/swmmtoolbox#11]
Hi @timcera,

Going to version 3.3.5 has created a breaking change in the extract method.

In our usage of the method we used to call it this way : 
``` python
extract(r"sample.out", ["system", "Rainfall", "Rainfall"])
```
Which was fine with 3.3.2 but in the new 3.3.5 this now results in 
```
Traceback (most recent call last):
  File "C:/Users/Florian DORRE/swmm_extract.py", line 5, in <module>
    extract(r"sample.out", ["system", "Rainfall", "Rainfall"])
  File "C:\Users\Florian DORRE\Envs\test_swmmtoolbox\lib\site-packages\swmmtoolbox\swmmtoolbox.py", line 745, in extract
    words = tsutils.make_list(label, n=3)
  File "C:\Users\Florian DORRE\Envs\test_swmmtoolbox\lib\site-packages\tstoolbox\tsutils.py", line 901, in make_list
    strorlist, n, kwdname
ValueError: 
*
*   The list ['system'] for "" should have 3 members according to
*   function requirements.
*
```

Of course a fix to that on our side would be to use the syntax like below that is working fine : 
``` python 
extract(r"sample.out", ["system,Rainfall,Rainfall"])
```

Would it be possible to add a specific condition if the parameter is already a list like it was before ?

**Comment by timcera** [comment]
Fixed in version 3.4.1.   Apologies that it took so long.
